#!/usr/bin/env bash
# Check if the number of parameters is less than 4
if [ "$#" -lt 4 ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

# Extract parameters
file_path="$1"
server_ip="$2"
username="$3"
ssh_key_path="$4"

# Transfer the file using scp with strict host key checking disabled
scp -o StrictHostKeyChecking=no -i "$ssh_key_path" "$file_path" "$username@$server_ip":~/

# Check if scp command was successful
if [ $#	-eq 0 ]; then
    echo "File transfer successful!"
else
    echo "Error transferring the file."
fi
