#!/bin/bash
#script that pings an IP address passed as an argument

# Check if an argument is provided
if [ $# -eq 0 ]; then
    echo "Usage: $0 {IP_ADDRESS}"
    exit 1
fi

# Validate if the provided argument is a valid IP address
if [[ ! $1 =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
    echo "Invalid IP address format. Please provide a valid IP address."
    exit 1
fi

# Ping the IP address 5 times
ping -c 5 "$1"
