#!/usr/bin/env bash
#Script Creates the file /var/run/myscript.pid containing its PID

# Function to handle signals
signal_handler()
{
	case $1 in
		SIGTERM|SIGQUIT)
			echo "I hate the kill command"
			rm /var/run/myscript.pid
			exit ;;
		SIGINT)
			echo "Y U no love me?!" ;;
		*) ;;
	esac
}

# Trap signals and execute signal_handler function
trap 'signal_handler SIGTERM' SIGTERM
trap 'signal_handler SIGQUIT' SIGQUIT
trap 'signal_handler SIGINT' SIGINT

# Create the PID file
echo "$$" > /var/run/myscript.pid

# Infinite loop
while true; do
	echo "To infinity and beyond"
	sleep 1
done
