#!/bin/bash
#script that configures an Ubuntu server with the below requirements

# Check if the script is running on Docker
if grep -q docker /proc/1/cgroup; then
    echo "Running on Docker. Modifying hosts file..."
    # Update localhost and facebook.com entries in /etc/hosts
    sudo sed -i 's/127\.0\.0\.1\slocalhost/127.0.0.2 localhost/' /etc/hosts
    sudo sed -i 's/facebook\.com/8.8.8.8 facebook.com/' /etc/hosts
    echo "Changes applied."
else
    echo "This script should be run on a Docker container."
    exit 1
fi
